upgraded restart script to accept arguments as service name; multiple arguments accepted - restart each; no arguments accepted - restart all

diff --git a/restart b/restart
--- a/restart
+++ b/restart
@@ -1,18 +1,18 @@
 #!/bin/bash
 MY_PATH=$(dirname "$0")
-MY_PATH=$(cd "$MY_PATH" && pwd) 
+MY_PATH=$(cd "$MY_PATH" && pwd)
 
 # lets check if config exists
 if [ ! -f $MY_PATH/config.yaml ]; then
-    echo "Configuration not found! Please create config.yaml from config.yaml.template and try again."
-    exit 1
+  echo "Configuration not found! Please create config.yaml from config.yaml.template and try again."
+  exit 1
 fi
 
 # lets load yaml parser function (fn: parse_yaml)
 source $MY_PATH/scripts/parse_yaml
 eval $(parse_yaml $MY_PATH/config.yaml)
 
-if [ $sensors_measureAqi = true ]; then
+function aqi() {
   if ! screen -list | grep -q "aqi"; then
     echo "starting AQI sensor... screen: aqi"
     screen -S aqi -d -m $MY_PATH/sensors/aqi.py
@@ -22,9 +22,9 @@ if [ $sensors_measureAqi = true ]; then
     echo "restarting AQI sensor... screen: aqi"
     screen -S aqi -d -m $MY_PATH/sensors/aqi.py
   fi
-fi
+}
 
-if [ $sensors_measureTemperature = true ]; then
+function temp() {
   if ! screen -list | grep -q "temp"; then
     echo "starting Temp sensor... screen: temp"
     screen -S temp -d -m $MY_PATH/sensors/temp.py
@@ -34,9 +34,9 @@ if [ $sensors_measureTemperature = true ]; then
     echo "restarting Temp sensor... screen: temp"
     screen -S temp -d -m $MY_PATH/sensors/temp.py
   fi
-fi
+}
 
-if [ $sensors_useCamera = true ]; then
+function camera() {
   if ! screen -list | grep -q "camera"; then
     echo "starting camera live stream... screen: camera"
     screen -S camera -d -m $MY_PATH/sensors/camera.sh
@@ -46,4 +46,32 @@ if [ $sensors_useCamera = true ]; then
     echo "restarting camera live stream... screen: camera"
     screen -S camera -d -m $MY_PATH/sensors/camera.sh
   fi
+}
+
+function checkAllServices() {
+  for var in "$@"; do
+    if ([ $var = "aqi" ] && [ $sensors_measureAqi = true ]); then
+      aqi
+    fi
+
+    if ([ $var = "temp" ] && [ $sensors_measureTemperature = true ]); then
+      temp
+    fi
+
+    if ([ $var = "camera" ] && [ $sensors_useCamera = true ]); then
+      camera
+    fi
+  done
+}
+
+function restartAllServices() {
+  aqi
+  temp
+  camera
+}
+
+if [ $# -eq 0 ]; then
+  restartAllServices
+else
+  checkAllServices $@
 fi
